// Code generated by "stringer -type LayerType -linecomment"; DO NOT EDIT.

package convnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerInput-1]
	_ = x[LayerRelu-2]
	_ = x[LayerSigmoid-3]
	_ = x[LayerTanh-4]
	_ = x[LayerDropout-5]
	_ = x[LayerConv-6]
	_ = x[LayerPool-7]
	_ = x[LayerLRN-8]
	_ = x[LayerSoftmax-9]
	_ = x[LayerRegression-10]
	_ = x[LayerFC-11]
	_ = x[LayerMaxout-12]
	_ = x[LayerSVM-13]
}

const _LayerType_name = "inputrelusigmoidtanhdropoutconvpoollrnsoftmaxregressionfcmaxoutsvm"

var _LayerType_index = [...]uint8{0, 5, 9, 16, 20, 27, 31, 35, 38, 45, 55, 57, 63, 66}

func (i LayerType) String() string {
	i -= 1
	if i < 0 || i >= LayerType(len(_LayerType_index)-1) {
		return "LayerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LayerType_name[_LayerType_index[i]:_LayerType_index[i+1]]
}
