// Code generated by "stringer -type TrainerMethod -linecomment"; DO NOT EDIT.

package convnet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethodSGD-0]
	_ = x[MethodAdam-1]
	_ = x[MethodADAGrad-2]
	_ = x[MethodADADelta-3]
	_ = x[MethodWindowGrad-4]
	_ = x[MethodNetsterov-5]
}

const _TrainerMethod_name = "sgdadamadagradadadeltawindowgradnetsterov"

var _TrainerMethod_index = [...]uint8{0, 3, 7, 14, 22, 32, 41}

func (i TrainerMethod) String() string {
	if i < 0 || i >= TrainerMethod(len(_TrainerMethod_index)-1) {
		return "TrainerMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TrainerMethod_name[_TrainerMethod_index[i]:_TrainerMethod_index[i+1]]
}
